In [2]:
# Code written by Claude (Anthropic, Claude Opus 5.5) for Google Colab compatibility.
# Adapted from the install cell of demo_2/notebooks/fr/07_llm_and_rag_FP16.ipynb (IFT 6758).
# OPTIONAL: once per new Colab runtime (version 2025.07 = Python 3.11, T4 GPU).
INSTALL_COLAB = False  # Set to True to install, then back to False

import sys
import subprocess
from pathlib import Path
from importlib.metadata import version

REPO_URL = "https://github.com/Mahdi267/NHL-data-analysis.git"
REPO_DIR = Path("/content/NHL-data-analysis")
REQ_FILE = Path("/content/requirements_colab.txt")

# Detect Colab; otherwise the local .venv is used
try:
    import google.colab  # noqa: F401
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if not IN_COLAB:
    print("Local environment: install skipped (uv sync --extra llm in the terminal).")
elif not INSTALL_COLAB:
    print("Install skipped. Set INSTALL_COLAB = True on a new Colab runtime.")
else:
    if sys.version_info[:2] != (3, 11):
        raise RuntimeError("Python 3.11 required: Runtime → Change runtime type → version 2025.07.")

    # 1. Project code (public repository: no credentials)
    if not REPO_DIR.exists():
        subprocess.check_call(["git", "clone", REPO_URL, str(REPO_DIR)])
    else:
        subprocess.check_call(["git", "-C", str(REPO_DIR), "pull"])

    # 2. Same versions as local (uv.lock), except torch: we keep Colab's,
    #    built for its CUDA driver (the torch in the lock is a CUDA 13 build)
    subprocess.check_call([sys.executable, "-m", "pip", "install", "uv>=0.8,<1"])
    export = subprocess.check_output(
        [sys.executable, "-m", "uv", "export", "--frozen", "--extra", "llm",
         "--no-dev", "--no-hashes", "--no-emit-project"],
        cwd=REPO_DIR, text=True,
    )
    skip = ("torch==", "triton==", "nvidia-")
    lines = [line for line in export.splitlines() if not line.startswith(skip)]
    lines.append(f"torch=={version('torch').split('+')[0]}")  # Pin the torch already installed
    REQ_FILE.write_text("\n".join(lines))

    # 3. Install into the notebook's Python, then the project in editable mode
    uv_install = [sys.executable, "-m", "uv", "pip", "install", "--python", sys.executable]
    subprocess.check_call(uv_install + ["-r", str(REQ_FILE)])
    subprocess.check_call(uv_install + ["--no-deps", "-e", str(REPO_DIR)])
    print("Install done. Runtime → Restart session, then set INSTALL_COLAB = False.")

Local environment: install skipped (uv sync --extra llm in the terminal).

In [3]:
# Code written by Claude (Anthropic, Claude Opus 5.5) for Google Colab compatibility.
import os
from pathlib import Path

try:
    import google.colab  # noqa: F401
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

# Adjust to THIS notebook's folder (notebooks/ or visualizations/): relative paths depend on it
NOTEBOOK_DIR = Path("/content/NHL-data-analysis/ift6758/notebooks")
if IN_COLAB:
    os.chdir(NOTEBOOK_DIR)
print("Working directory:", Path.cwd())

from ift6758.llm.qwen_utils import check_env
check_env()  # Should show Python 3.11 and CUDA GPU: Tesla T4

Working directory: /Users/jcforget/Maitrise/Cours/IFT 6758/Projet/Github/NHL-data-analysis/ift6758/notebooks
Python: 3.11.15
NumPy: 1.26.4 | pandas: 2.3.3
Transformers: 5.17.0
Sentence Transformers: 6.1.0
CUDA GPU: Unavailable — CPU/Apple GPU fallback

In [4]:
%load_ext autoreload
%autoreload 2

In [5]:
import json
from pathlib import Path
import pandas as pd
import requests
from ift6758.llm.get_better import (
    extract_text,
    load_function,
    format_test_report,
    all_passed,
)
from ift6758.llm.chat import confirm
from ift6758.llm.prompts import PROFILES
from ift6758.llm.qwen_log import create_log, log_call
from ift6758.llm.qwen_utils import (
    load_qwen,
    ask_qwen,
    check_env,
)
from ift6758.llm.rag import (
    load_doc,
    extract_section,
    split_doc,
    load_embedder,
    embed,
    retrieve,
    format_context,
    DOCS_DIR,
)
from ift6758.llm.test_tidy_llm import run_tidy_tests, compare_to_reference, add_goalie_stops

check_env()  # Demo 2, for reproductibility

Python: 3.11.15
NumPy: 1.26.4 | pandas: 2.3.3
Transformers: 5.17.0
Sentence Transformers: 6.1.0
CUDA GPU: Unavailable — CPU/Apple GPU fallback

In [6]:
# Code adapted from demo 2
GAME_ID = 2022030411
raw_path = Path(DOCS_DIR.parent / str(GAME_ID)[:4]) / f"{GAME_ID}.json"
print("Cached game:", raw_path.resolve())
if not raw_path.exists():
    response = requests.get(
        f"https://api-web.nhle.com/v1/gamecenter/{GAME_ID}/play-by-play", timeout=30
    )
    response.raise_for_status()
    downloaded = response.json()
    assert downloaded["id"] == GAME_ID and isinstance(downloaded["plays"], list)
    raw_path.parent.mkdir(parents=True, exist_ok=True)
    raw_path.write_text(response.text, encoding="utf-8")
game = json.loads(
    raw_path.read_text(encoding="utf-8")
)  # Converted from JSON to a Python object
assert game["id"] == GAME_ID and isinstance(game["plays"], list)
print(game["awayTeam"]["abbrev"], "at", game["homeTeam"]["abbrev"], game["gameDate"])

Cached game: /Users/jcforget/Maitrise/Cours/IFT 6758/Projet/Github/NHL-data-analysis/ift6758/data/2022/2022030411.json
FLA at VGK 2023-06-03

In [7]:
# Reference DataFrame: Mahdi's json2tidy, checked by hand against NHL.com (except x and y, not available)
reference = pd.read_csv(DOCS_DIR / "reference_tidy.csv")
REF_GAMES = {
    2022030411: DOCS_DIR.parent / str(GAME_ID)[:4] / "2022030411.json",
    2020020007: Path("../data/2020/2020020007.json"),  # Relative to ift6758/notebooks/ (ignored by git)
    2020020020: Path("../data/2020/2020020020.json"),
}
# Same download as the cell above, for the games that are not cached
for gid, path in REF_GAMES.items():
    if not Path(path).exists():
        response = requests.get(
            f"https://api-web.nhle.com/v1/gamecenter/{gid}/play-by-play", timeout=30
        )
        response.raise_for_status()
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        Path(path).write_text(response.text, encoding="utf-8")
print(reference.groupby("game_id")["event_type"].value_counts().unstack())

event_type  goal  shot-on-goal
game_id
2020020007     4            55
2020020020     9            64
2022030411     7            62

## Q3 plan: one generation per level of context

Same prompt (`tidy_task`, only the assignment + the interface) for every variant, `do_sample=False`.
A single generation per variant, to isolate the effect of the context (no refinement loop:
generic tests do not measure correctness, and exact tests would give the answer to the model).

| Variante | Contexte |
|---|---|
| C0 | None |
| C1 | RAG on the API documentation (Zmalski), same query as Q1 |
| C2 – C3 | *Context built with the help of Claude* |
| C2 | JSON sample: first shot and first goal of the game (not chosen) |
| C3 | JSON sample chosen to show the traps (shot, goal at 1451, empty net goal) |

Evaluation: 3 generic tests (`run_tidy_tests`) + comparison with the reference (`compare_to_reference`).

In [8]:
# 4 levels of context, same prompt (tidy_task) for all. One generation per level.
CONTEXTS = {}

# C0 : no context
CONTEXTS["C0"] = {"label": "no context", "context": None, "retrieved": None}

# C1 : a little context = RAG on the NHL API documentation (same code as Q1, cell 2)
zmalski_file = "zmalski-nhl-api-reference.md"
zmalski_url = "https://raw.githubusercontent.com/Zmalski/NHL-API-Reference/main/README.md"
text = load_doc(zmalski_url, zmalski_file)
section = extract_section(text, "# NHL Web API Documentation", "# NHL Stats API Documentation")
chunks = split_doc(section)
embedder = load_embedder()
vectors = embed(chunks, embedder)
# Same retrieval query as Q1: finds the "Get Play By Play" endpoint (passage 35)
rag_results = retrieve(PROFILES["gen_code"]["retrieval_query"], chunks, vectors, embedder, k=PROFILES["gen_tidy"]["k"])
CONTEXTS["C1"] = {
    "label": "RAG NHL API doc",
    "context": format_context(rag_results, source=zmalski_file),
    "retrieved": rag_results,
}

# ____ DISCLAMER : CONTEXT BEYOND THIS POINT WAS PROPOSED BY CLAUDE TO HELP GET DECENT RESULTS ____

def build_sample_context(game, sample_events, source):
    """Sample of the real game JSON (game level, chosen plays, their players), in the format of retrieve().
    Same code as the previous context cell, put in a function to build C2 and C3.

    :param game: Game JSON
    :type game: dict
    :param sample_events: eventId of the plays to show
    :type sample_events: tuple
    :param source: Source label for format_context
    :type source: str
    :return: context, passages
    :rtype: tuple[str, list[dict]]
    """
    # Match: just as peek_game_level
    game_level = {
        "id": game["id"],
        "season": game["season"],
        "gameType": game["gameType"],
        "homeTeam": {"id": game["homeTeam"]["id"], "abbrev": game["homeTeam"]["abbrev"]},
        "awayTeam": {"id": game["awayTeam"]["id"], "abbrev": game["awayTeam"]["abbrev"]},
    }
    # Chosen plays and their position in game["plays"]
    sample_plays = [(i, p) for i, p in enumerate(game["plays"]) if p["eventId"] in sample_events]
    # peek_shooter_keys ("PlayerId" in k) + goalie
    player_ids = {
        v for _, p in sample_plays for k, v in p["details"].items()
        if "PlayerId" in k or k == "goalieInNetId"
    }
    # rosterSpots: same search as peek_player_name, without useless fields
    roster = [
        {key: r[key] for key in ("playerId", "teamId", "firstName", "lastName")}
        for r in game["rosterSpots"] if r["playerId"] in player_ids
    ]
    # Same format as retrieve() to use format_context()
    passages = [("game level", game_level)]
    passages += [(f"plays[{i}]", p) for i, p in sample_plays]
    passages += [("rosterSpots (players of the plays above)", roster)]
    passages = [
        {"rank": rank, "index": label, "score": None, "text": json.dumps(part, indent=2)}
        for rank, (label, part) in enumerate(passages, start=1)
    ]
    context = (
        "Excerpts of one real NHL play-by-play game JSON. All games have the same structure.\n\n"
        + format_context(passages, source=source)
    )
    return context, passages

# C2 : medium context = first shot on goal and first goal of the game (not chosen by us)
first_shot = next(p["eventId"] for p in game["plays"] if p["typeDescKey"] == "shot-on-goal")
first_goal = next(p["eventId"] for p in game["plays"] if p["typeDescKey"] == "goal")
c2_context, c2_passages = build_sample_context(game, (first_shot, first_goal), f"{GAME_ID}.json")
CONTEXTS["C2"] = {"label": f"JSON sample, events {first_shot}/{first_goal}", "context": c2_context, "retrieved": c2_passages}

# C3 : a lot of context = plays chosen to show every trap (shot, goal at 1451, empty net goal)
c3_context, c3_passages = build_sample_context(game, (55, 87, 1001), f"{GAME_ID}.json")
CONTEXTS["C3"] = {"label": "JSON sample, events 55/87/1001", "context": c3_context, "retrieved": c3_passages}

for name, c in CONTEXTS.items():
    print(name, "|", c["label"], "|", len(c["context"] or ""), "characters")

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

C0 | no context | 0 characters
C1 | RAG NHL API doc | 1605 characters
C2 | JSON sample, events 55/87 | 2296 characters
C3 | JSON sample, events 55/87/1001 | 3284 characters

In [9]:
# I wrote this prompt reusing the structure proposed by Claude and by the article, but with only the information
# that I knew myself: the wanted format (like Mahdi's) and the information asked by the assignment.
# - The JSON is the play-by-play of one game from the NHL web API:
#  https://api-web.nhle.com/v1/gamecenter/{game_id}/play-by-play
tidy_task = """
Write a Python function json2tidy_llm(raw_data).
Goal: convert all the events of one NHL game into a tidy pandas DataFrame.

Input:
- raw_data is either a str (path to a JSON file, read as UTF-8) or a dict (already loaded).

Task:
- Keep only shots on goal and goals. Ignore missed shots and blocked shots.
- One row per kept event, uniquely identified by the game ID and the event ID.
- For each event include at least: game ID, event ID, season, game type, period, time in the period,
  the team that took the shot, whether it is a shot or a goal, the coordinates on the ice,
  the shooter name, the goalie name, the shot type, whether the net was empty,
  and, for goals, whether the goal was scored at even strength, shorthanded or on the power play.
- Keep unavailable values as missing. Never replace them with 0 or False.

Output interface (used by automated tests):
- Columns: game_id, event_id, season, game_type, period, time, team_id, event_type,
  x_coord, y_coord, shooter, goalie, shot_type, empty_net, strength.
- event_type is "shot-on-goal" or "goal". game_type is the numeric game type of the game.
- shooter and goalie are full names: "First Last".
- empty_net is True or False.
- strength is "even", "shorthanded" or "power play" for goals, and missing for shots.

Use pandas and json. Include imports and a docstring.
Return only json2tidy_llm and its imports in a Python code block.
"""

In [10]:
model, tokenizer, device = load_qwen()
log_path = create_log()
print("Log :", log_path)

# Code suggested by Claude to embelish presentation
def banner(title):
    print(f"\n{'=' * 15} {title} {'=' * 15}")

Loading weights:   0%|          | 0/398 [00:00<?, ?it/s]

Log : /Users/jcforget/Maitrise/Cours/IFT 6758/Projet/Github/NHL-data-analysis/logs/chat_2026-10-19_17-07-58.jsonl

In [11]:
GENERATED_DIR = DOCS_DIR.parent.parent / "llm" / "generated"  # Generated code of each variant, for the report
TASK_VERSION = "tidy_naive_v0"


def run_variant(name, task, ctx):
    """One generation with one context, then extraction, tests and comparison with the reference.
    Same steps as the Q1 loop, without the refinement.

    :param name: Variant name (C0, C1...)
    :type name: str
    :param task: Task prompt
    :type task: str
    :param ctx: Entry of CONTEXTS
    :type ctx: dict
    :return: One row of the summary table
    :rtype: dict
    """
    banner(f"{name} : code generation ({ctx['label']})")
    gen_result = ask_qwen(
        model=model,
        tokenizer=tokenizer,
        log_path=log_path,
        prompt=task,
        context=ctx["context"],
        profile=PROFILES["gen_tidy"],
        extra={
            "variant": name,
            "context_label": ctx["label"],
            "task_version": TASK_VERSION,
            "retrieved": ctx["retrieved"],
        },
    )
    row = {
        "variant": name,
        "context": ctx["label"],
        "n_token_in": gen_result["n_token_in"],
        "n_token_out": gen_result["n_token_out"],
        "duration_s": round(gen_result["duration_s"], 1),
        "truncated": gen_result["n_token_out"] >= PROFILES["gen_tidy"]["max_new_tokens"],
    }

    # Extraction and human in the loop validation
    try:
        tidy_code = extract_text(gen_result["answer"], tag="code")
    except ValueError as e:
        tidy_code = gen_result["answer"]  # no code generated
        test_results = {"0. Code extraction": f"ERROR : {e}"}
    else:
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        (GENERATED_DIR / f"tidy_{name}.py").write_text(tidy_code, encoding="utf-8")
        if not confirm("Execute and test code ?"):
            row["tests"] = "not executed"
            return row
        try:
            fn = load_function(tidy_code, "json2tidy_llm")
        except Exception as e:  # SyntaxError, missing import...
            test_results = {"0. Code loading": f"ERROR : {type(e).__name__}: {e}"}
        else:
            test_results = run_tidy_tests(fn)
            # Comparison with the reference (can crash if a column is missing)
            try:
                comparison = compare_to_reference(fn, reference, REF_GAMES)
            except Exception as e:
                row["comparison"] = f"ERROR : {type(e).__name__}: {e}"
            else:
                row.update(comparison["rows"])
                row.update({f"{col} %": pct for col, pct in comparison["agreement_%"].items()})
                row["mismatch_examples"] = comparison["mismatch_examples"]

    report = format_test_report(test_results)
    banner(f"{name} : test results")
    print(report)
    row["tests_passed"] = f"{sum(s == 'OK' for s in test_results.values())}/{len(test_results)}"
    row["all_passed"] = all_passed(test_results)
    row["report"] = report
    return row

In [12]:
summary = []  # One row per variant, seen at the end
for name in ["C0", "C1", "C2", "C3"]:  # Long ....
    summary.append(run_variant(name, tidy_task, CONTEXTS[name]))

=============== C0 : code generation (no context) ===============

```python
import pandas as pd
import json
import numpy as np

def json2tidy_llm(raw_data):
    """
    Convert NHL game events (shots on goal and goals) into a tidy pandas DataFrame.

    Parameters:
    raw_data (str or dict): Either a path to a JSON file (read as UTF-8) or a loaded JSON dictionary.

    Returns:
    pandas.DataFrame: Tidy DataFrame with one row per shot or goal event, including:
        - game_id, event_id, season, game_type, period, time
        - team_id, event_type (either "shot-on-goal" or "goal")
        - x_coord, y_coord, shooter, goalie, shot_type, empty_net
        - strength (only for goals: "even", "shorthanded", "power play"; missing for shots)
    """
    # Load data
    if isinstance(raw_data, str):
        with open(raw_data, 'r', encoding='utf-8') as f:
            data = json.load(f)
    else:
        data = raw_data

    # Initialize list to store events
    events = []

    # Process each game
    for game in data.get('games', []):
        game_id = game.get('game_id')
        season = game.get('season')
        game_type = game.get('game_type')

        for event in game.get('events', []):
            event_id = event.get('event_id')
            period = event.get('period')
            time = event.get('time')
            team_id = event.get('team_id')
            event_type = event.get('event_type')

            # Only keep shots on goal and goals
            if event_type not in ['shot_on_goal', 'goal']:
                continue

            # Extract coordinates
            x_coord = event.get('x')
            y_coord = event.get('y')

            # Extract shooter and goalie
            shooter = event.get('shooter')
            goalie = event.get('goalie')

            # Extract shot type
            shot_type = event.get('shot_type')

            # Extract empty net
            empty_net = event.get('empty_net')

            # Extract strength (only for goals)
            strength = None
            if event_type == 'goal':
                strength = event.get('strength')

            # Build event dictionary
            event_dict = {
                'game_id': game_id,
                'event_id': event_id,
                'season': season,
                'game_type': game_type,
                'period': period,
                'time': time,
                'team_id': team_id,
                'event_type': event_type,
                'x_coord': x_coord,
                'y_coord': y_coord,
                'shooter': shooter,
                'goalie': goalie,
                'shot_type': shot_type,
                'empty_net': empty_net,
                'strength': strength
            }

            events.append(event_dict)

    # Convert to DataFrame
    df = pd.DataFrame(events)

    # Ensure proper data types and missing values
    df['game_id'] = df['game_id'].astype(str)
    df['event_id'] = df['event_id'].astype(str)
    df['season'] = df['season'].astype(str)
    df['game_type'] = df['game_type'].astype(int)
    df['period'] = df['period'].astype(int)
    df['time'] = df['time'].astype(str)
    df['team_id'] = df['team_id'].astype(str)

    # Convert boolean fields to proper booleans
    bool_columns = ['empty_net']
    for col in bool_columns:
        if col in df.columns:
            df[col] = df[col].apply(lambda x: True if pd.isna(x) or x is True else False)

    # Ensure strength is properly formatted
    df['strength'] = df['strength'].fillna('')
    df['strength'] = df['strength'].apply(lambda x: x if x in ['even', 'shorthanded', 'power play'] else '')

    # Filter out empty strength (only for goals)
    df = df[df['event_type'] == 'goal'].copy()
    df['strength'] = df['strength'].fillna('')

    # Final cleanup: ensure all required columns are present
    required_columns = ['game_id', 'event_id', 'season', 'game_type', 'period', 'time',
                        'team_id', 'event_type', 'x_coord', 'y_coord', 'shooter', 'goalie',
                        'shot_type', 'empty_net', 'strength']

    # Reconstruct with required columns
    df = df[required_columns]

    # Ensure event_type is correct
    df['event_type'] = df['event_type'].map({'shot_on_goal': 'shot-on-goal', 'goal': 'goal'})

    # Return DataFrame
    return df
```

371 tokens in, 1032 generated, 225.3 s
Execute and test code ? (y/n) :  -> o (auto)

=============== C0 : test results ===============
0/3 tests passed
Test: 1. Structure, Status: ERROR : KeyError: 'game_id'
Test: 2. Rows, Status: ERROR : KeyError: 'game_id'
Test: 3. Values format, Status: ERROR : KeyError: 'game_id'

=============== C1 : code generation (RAG NHL API doc) ===============

```python
import pandas as pd
import json
from typing import Union

def json2tidy_llm(raw_data: Union[str, dict]) -> pd.DataFrame:
    """
    Convert NHL game events (shots on goal and goals) into a tidy pandas DataFrame.

    Parameters:
    raw_data (str or dict): Either a path to a JSON file (read as UTF-8) or a dict containing the data.

    Returns:
    pd.DataFrame: A DataFrame with columns: game_id, event_id, season, game_type, period, time,
                  team_id, event_type, x_coord, y_coord, shooter, goalie, shot_type, empty_net, strength.
    - event_type is "shot-on-goal" or "goal".
    - game_type is the numeric game type.
    - shooter and goalie are full names (e.g., "First Last").
    - empty_net is True or False.
    - strength is "even", "shorthanded", or "power play" for goals; missing for shots.
    - Missing values are preserved as NaN.
    """
    # Load data
    if isinstance(raw_data, str):
        with open(raw_data, 'r', encoding='utf-8') as f:
            data = json.load(f)
    else:
        data = raw_data

    # Extract events (assume data structure has 'events' or similar)
    events = data.get('events', []) if isinstance(data, dict) else []

    # Initialize list for results
    rows = []

    for event in events:
        event_id = event.get('event_id')
        game_id = event.get('game_id')
        season = event.get('season')
        game_type = event.get('game_type')
        period = event.get('period')
        time = event.get('time')
        team_id = event.get('team_id')
        event_type = event.get('event_type')

        # Only keep shots on goal and goals
        if event_type not in ['shot_on_goal', 'goal']:
            continue

        # Extract coordinates
        x_coord = event.get('x')
        y_coord = event.get('y')

        # Extract shooter and goalie
        shooter = event.get('shooter') or event.get('player_name')
        goalie = event.get('goalie') or event.get('goalie_name')

        # Format names to "First Last"
        shooter = shooter.split(' ')[-1] if shooter and isinstance(shooter, str) else ""
        goalie = goalie.split(' ')[-1] if goalie and isinstance(goalie, str) else ""

        # Extract shot type
        shot_type = event.get('shot_type')

        # Empty net flag
        empty_net = event.get('empty_net', False)

        # Strength for goals only
        strength = None
        if event_type == 'goal':
            strength = event.get('strength')

        # Add row
        rows.append({
            'game_id': game_id,
            'event_id': event_id,
            'season': season,
            'game_type': game_type,
            'period': period,
            'time': time,
            'team_id': team_id,
            'event_type': event_type,
            'x_coord': x_coord,
            'y_coord': y_coord,
            'shooter': shooter,
            'goalie': goalie,
            'shot_type': shot_type,
            'empty_net': empty_net,
            'strength': strength
        })

    # Convert to DataFrame
    df = pd.DataFrame(rows)

    # Ensure correct data types and missing values
    df['event_type'] = df['event_type'].str.upper()
    df['event_type'] = df['event_type'].replace({'SHOT_ON_GOAL': 'shot-on-goal', 'GOAL': 'goal'})

    # Ensure strength is only for goals and missing for shots
    df['strength'] = df['strength'].fillna('')
    df['strength'] = df['strength'].replace({'even': 'even', 'shorthanded': 'shorthanded', 'power play': 'power play'})

    # Convert to proper types
    df['game_id'] = pd.to_numeric(df['game_id'], errors='coerce')
    df['event_id'] = pd.to_numeric(df['event_id'], errors='coerce')
    df['season'] = pd.to_numeric(df['season'], errors='coerce')
    df['game_type'] = pd.to_numeric(df['game_type'], errors='coerce')
    df['period'] = pd.to_numeric(df['period'], errors='coerce')
    df['time'] = pd.to_numeric(df['time'], errors='coerce')
    df['team_id'] = pd.to_numeric(df['team_id'], errors='coerce')

    # Ensure event_type is string
    df['event_type'] = df['event_type'].astype(str)

    return df
```

910 tokens in, 1033 generated, 231.6 s
Execute and test code ? (y/n) :  -> o (auto)

=============== C1 : test results ===============
0/3 tests passed
Test: 1. Structure, Status: ERROR : KeyError: 'event_type'
Test: 2. Rows, Status: ERROR : KeyError: 'event_type'
Test: 3. Values format, Status: ERROR : KeyError: 'event_type'

=============== C2 : code generation (JSON sample, events 55/87) ===============

```python
import pandas as pd
import json
from typing import Union

def json2tidy_llm(raw_data: Union[str, dict]) -> pd.DataFrame:
    """
    Convert an NHL game JSON into a tidy pandas DataFrame containing only shots on goal and goals.

    Input:
        raw_data: Either a string path to a JSON file (read as UTF-8) or a dictionary representing the game data.

    Output:
        A pandas DataFrame with the following columns:
        - game_id: the game ID (int)
        - event_id: the event ID (int)
        - season: the season (int)
        - game_type: the game type (int)
        - period: the period number (int)
        - time: time in the period (str, e.g., "01:29")
        - team_id: the team that took the shot (int)
        - event_type: "shot-on-goal" or "goal"
        - x_coord: x coordinate on ice (int)
        - y_coord: y coordinate on ice (int)
        - shooter: full name of shooter ("First Last")
        - goalie: full name of goalie ("First Last")
        - shot_type: type of shot (str)
        - empty_net: True/False if net was empty
        - strength: "even", "shorthanded", "power play" for goals; missing for shots

    Notes:
        - Only shots on goal and goals are included.
        - Missing values are preserved as NaN.
        - event_type is derived from typeDescKey.
        - strength is derived from situationCode (e.g., 1451 -> even strength).
        - For shots, strength is missing.
        - For goals, strength is inferred from situationCode (e.g., 1451 = even, 1452 = shorthanded, 1453 = power play).
    """
    # Load data
    if isinstance(raw_data, str):
        with open(raw_data, 'r', encoding='utf-8') as f:
            data = json.load(f)
    else:
        data = raw_data

    # Extract game metadata
    game_info = data.get("game", {})
    game_id = data.get("id")
    season = data.get("season")
    game_type = data.get("gameType")

    # Extract plays
    plays = data.get("plays", [])

    # Map situation codes to strength
    strength_map = {
        1451: "even",
        1452: "shorthanded",
        1453: "power play"
    }

    rows = []

    for play in plays:
        event = play
        event_id = event.get("eventId")
        period = event["periodDescriptor"].get("number")
        time_in_period = event.get("timeInPeriod")
        time_remaining = event.get("timeRemaining")
        situation_code = event.get("situationCode")
        team_id = event.get("eventOwnerTeamId")
        type_code = event.get("typeCode")
        type_desc_key = event.get("typeDescKey")

        # Only include shots on goal and goals
        if type_desc_key not in ["shot-on-goal", "goal"]:
            continue

        # Extract details
        details = event.get("details", {})
        x_coord = details.get("xCoord")
        y_coord = details.get("yCoord")
        zone_code = details.get("zoneCode")
        shot_type = details.get("shotType")
        shooting_player_id = details.get("shootingPlayerId")
        scoring_player_id = details.get("scoringPlayerId")
        goalie_in_net_id = details.get("goalieInNetId")

        # Determine event type
        event_type = "shot-on-goal" if type_desc_key == "shot-on-goal" else "goal"

        # Get player names from rosterSpots
        roster_spots = data.get("rosterSpots", [])
        shooter_name = None
        goalie_name = None

        for player in roster_spots:
            if player["playerId"] == shooting_player_id:
                shooter_name = f"{player['firstName']['default']} {player['lastName']['default']}"
            elif player["playerId"] == goalie_in_net_id:
                goalie_name = f"{player['firstName']['default']} {player['lastName']['default']}"

        # Determine empty net
        empty_net = details.get("emptyNet", False) if "emptyNet" in details else False

        # Determine strength for goals only
        strength = None
        if event_type == "goal":
            strength = strength_map.get(situation_code, None)

        # Append row
        rows.append({
            "game_id": game_id,
            "event_id": event_id,
            "season": season,
            "game_type": game_type,
            "period": period,
            "time": time_in_period,
            "team_id": team_id,
            "event_type": event_type,
            "x_coord": x_coord,
            "y_coord": y_coord,
            "shooter": shooter_name,
            "goalie": goalie_name,
            "shot_type": shot_type,
            "empty_net": empty_net,
            "strength": strength
        })

    # Convert to DataFrame
    df = pd.DataFrame(rows)

    # Ensure correct data types and handle missing values
    df["game_id"] = pd.to_numeric(df["game_id"], errors="coerce")
    df["event_id"] = pd.to_numeric(df["event_id"], errors="coerce")
    df["season"] = pd.to_numeric(df["season"], errors="coerce")
    df["game_type"] = pd.to_numeric(df["game_type"], errors="coerce")
    df["period"] = pd.to_numeric(df["period"], errors="coerce")

    return df
```

1332 tokens in, 1245 generated, 283.2 s
Execute and test code ? (y/n) :  -> o (auto)

=============== C2 : test results ===============
2/3 tests passed
Test: 1. Structure, Status: OK
Test: 2. Rows, Status: OK
Test: 3. Values format, Status: FAIL : Every shot and goal has a shooter, but 7 rows have none ({'goal': 7})

=============== C3 : code generation (JSON sample, events 55/87/1001) ===============

```python
import pandas as pd
import json
from typing import Union

def json2tidy_llm(raw_data: Union[str, dict]) -> pd.DataFrame:
    """
    Convert an NHL game JSON into a tidy pandas DataFrame containing only shots on goal and goals.

    Input:
        raw_data: Either a string path to a JSON file (read as UTF-8) or a dictionary containing the game data.

    Output:
        A pandas DataFrame with the following columns:
        - game_id: the game ID (int)
        - event_id: the event ID (int)
        - season: the season (int)
        - game_type: the game type (int)
        - period: the period number (int)
        - time: time in the period (str, e.g., "01:29")
        - team_id: the team that took the shot (int)
        - event_type: "shot-on-goal" or "goal"
        - x_coord: x coordinate on ice (int)
        - y_coord: y coordinate on ice (int)
        - shooter: full name of shooter ("First Last")
        - goalie: full name of goalie ("First Last")
        - shot_type: type of shot (str)
        - empty_net: True/False if net was empty
        - strength: "even", "shorthanded", or "power play" for goals; missing for shots

    Notes:
        - Only shots on goal and goals are included.
        - Missing values are preserved as NaN.
        - event_type is derived from typeDescKey.
        - strength is derived from situationCode (e.g., 1451 = even, 1551 = even, 1651 = shorthanded, etc.).
        - For shots, strength is missing.
        - For goals, strength is inferred from situationCode.
    """
    # Load data
    if isinstance(raw_data, str):
        with open(raw_data, 'r', encoding='utf-8') as f:
            data = json.load(f)
    else:
        data = raw_data

    # Extract game metadata
    game_info = data.get("game", {})
    game_id = data.get("id")
    season = data.get("season")
    game_type = data.get("gameType")

    # Extract plays
    plays = data.get("plays", [])

    # Map situation codes to strength
    strength_map = {
        1451: "even",
        1551: "even",
        1651: "shorthanded",
        1751: "power play",
        1851: "power play",
        1951: "power play"
    }

    rows = []

    for play in plays:
        event = play
        event_id = event.get("eventId")
        period_desc = event.get("periodDescriptor")
        period = period_desc.get("number")
        time_in_period = event.get("timeInPeriod")
        time_remaining = event.get("timeRemaining")
        situation_code = event.get("situationCode")
        type_code = event.get("typeCode")
        type_desc_key = event.get("typeDescKey")

        # Only include shots on goal and goals
        if type_desc_key not in ["shot-on-goal", "goal"]:
            continue

        # Extract team ID (eventOwnerTeamId)
        team_id = event.get("eventOwnerTeamId")

        # Extract coordinates
        x_coord = event.get("details", {}).get("xCoord")
        y_coord = event.get("details", {}).get("yCoord")

        # Extract shot type
        shot_type = event.get("details", {}).get("shotType")

        # Extract shooter and goalie
        shooter_id = event.get("details", {}).get("shootingPlayerId")
        goalie_id = event.get("details", {}).get("goalieInNetId")

        # Get player names from rosterSpots
        roster = data.get("rosterSpots", [])
        player_map = {p["playerId"]: f"{p['firstName']['default']} {p['lastName']['default']}" for p in roster}

        shooter = player_map.get(shooter_id, None)
        goalie = player_map.get(goalie_id, None)

        # Determine event type
        event_type = "shot-on-goal" if type_desc_key == "shot-on-goal" else "goal"

        # Determine empty net
        empty_net = False
        if event_type == "goal":
            # Check if goalie is in net (zoneCode might help, but we use logic from details)
            # In NHL, empty net is when goalie is not in net (e.g., zoneCode is N or O, but goalie is not present)
            # However, in this data, we can infer from the goalie being in net
            # If goalie is not in net (e.g., goalieId is missing), then it's empty net
            # But in our data, goalieId is always present in goals
            # So we use: if goalie is not in net (e.g., goalieId is None), then empty net
            # But in our data, goalieId is always present
            # So we use: if goalie is not in net (zoneCode is N or O, and goalie is not in net), but no such field
            # Instead, we rely on the fact that if goalie is not in net, it's empty net
            # But in the data, goalieInNetId is always present
            # So we can't infer empty net from this
            # However, in the data, empty net is not explicitly defined
            # So we leave it as False by default
            # But in some cases, if goalie is not in net, it's empty net
            # We can check if goalie is in net: if goalieInNetId is present, then not empty net
            # But we don't have a field for that
            # So we leave empty_net as False
            pass

        # Determine strength for goals only
        strength = None
        if event_type == "goal":
            strength = strength_map.get(situation_code, None)

        # Create row
        row = {
            "game_id": game_id,
            "event_id": event_id,
            "season": season,
            "game_type": game_type,
            "period": period,
            "time": time_in_period,
            "team_id": team_id,
            "event_type": event_type,
            "x_coord": x_coord,
            "y_coord": y_coord,
            "shooter": shooter,
            "goalie": goalie,
            "shot_type": shot_type,
            "empty_net": empty_net,
            "strength": strength
        }

        rows.append(row)

    # Convert to DataFrame
    df = pd.DataFrame(rows)

    # Ensure correct data types
    df["game_id"] = pd.to_numeric(df["game_id"], errors="coerce")
    df["event_id"] = pd.to_numeric(df["event_id"], errors="coerce")
    df["season"] = pd.to_numeric(df["season"], errors="coerce")
    df["game_type"] = pd.to_numeric(df["game_type"], errors="coerce")
    df["period"] = pd.to_numeric(df["period"], errors="coerce")

    # Ensure time is string
    df["time"] = df["time"].astype(str)

    # Ensure coordinates are numeric or NaN
    df["x_coord"] = pd.to_numeric(df["x_coord"], errors="coerce")
    df["y_coord"] = pd.to_numeric(df["y_coord"], errors="coerce")

    # Ensure shooter, goalie are strings or NaN
    df["shooter"] = df["shooter"].fillna("").astype(str)
    df["goalie"] = df["goalie"].fillna("").astype(str)

    # Ensure shot_type is string or NaN
    df["shot_type"] = df["shot_type"].fillna("").astype(str)

    # Ensure strength is string or NaN
    df["strength"] = df["strength"].fillna("").astype(str)

    # Ensure empty_net is boolean
    df["empty_net"] = df["empty_net"].apply(lambda x: True if pd.notna(x) and x else False)

    return df
```

1734 tokens in, 1781 generated, 375.5 s
Execute and test code ? (y/n) :  -> o (auto)

=============== C3 : test results ===============
2/3 tests passed
Test: 1. Structure, Status: OK
Test: 2. Rows, Status: OK
Test: 3. Values format, Status: FAIL : Goal strength must be even, shorthanded or power play, got: {''}

In [13]:
summary_df = pd.DataFrame(summary).set_index("variant")
summary_df.drop(columns=["report", "mismatch_examples"], errors="ignore").T

variant,C0,C1,C2,C3
context,no context,RAG NHL API doc,"JSON sample, events 55/87","JSON sample, events 55/87/1001"
n_token_in,371,910,1332,1734
n_token_out,1032,1033,1245,1781
duration_s,225.3,231.6,283.2,375.5
truncated,False,False,False,False
comparison,ERROR : KeyError: 'game_id',ERROR : KeyError: 'event_type',NaN,NaN
tests_passed,0/3,0/3,2/3,2/3
all_passed,False,False,False,False
reference,NaN,NaN,201.0,201.0
llm,NaN,NaN,206.0,206.0
matched,NaN,NaN,201.0,201.0
missing,NaN,NaN,0.0,0.0
extra,NaN,NaN,5.0,5.0
season %,NaN,NaN,100.0,100.0
game_type %,NaN,NaN,100.0,100.0
period %,NaN,NaN,100.0,100.0
time %,NaN,NaN,100.0,100.0
team_id %,NaN,NaN,0.0,0.0
event_type %,NaN,NaN,100.0,100.0
x_coord %,NaN,NaN,100.0,100.0
y_coord %,NaN,NaN,100.0,100.0
shooter %,NaN,NaN,90.0,90.0
goalie %,NaN,NaN,100.0,99.5
shot_type %,NaN,NaN,100.0,100.0
empty_net %,NaN,NaN,99.5,99.5
strength %,NaN,NaN,90.0,0.0

In [14]:
logs = pd.read_json(log_path, lines=True)
logs[["variant", "context_label", "task_version", "n_token_in", "n_token_out", "duration_s"]]

,variant,context_label,task_version,n_token_in,n_token_out,duration_s
0,C0,no context,tidy_naive_v0,371,1032,225.256647
1,C1,RAG NHL API doc,tidy_naive_v0,910,1033,231.582212
2,C2,"JSON sample, events 55/87",tidy_naive_v0,1332,1245,283.249500
3,C3,"JSON sample, events 55/87/1001",tidy_naive_v0,1734,1781,375.462360

New section for the caracteristics implementation

In [15]:
stops_task = """
Write a Python function add_goalie_stops_llm(df).
Goal: add a feature "goalie_stops" to a tidy DataFrame of NHL shots and goals.

Input:
- df is a pandas DataFrame with one row per shot on goal or goal, already in chronological order
  inside each game. Columns include: game_id, event_id, event_type, goalie.
- event_type is "shot-on-goal" or "goal". goalie is the goalie's full name, missing when the net is empty.
- The context shows the first rows of a real DataFrame.

Rule for goalie_stops (number of shots stopped by the goalie so far in the game, current event included):
- If event_type is "shot-on-goal", add 1 to the counter of the corresponding goalie.
- If it is the first time in a game that a goalie stops a shot, the counter starts at 1, or at 0 if it is a goal.
- If there are previous events with that goalie in the same game, take the value from the last event
  and add 1 if the current event_type is "shot-on-goal".
- A game can have more than one goalie per team: keep one counter per goalie and per game.

Requirements:
- Do not sort the rows. event_id is not in chronological order.
- If goalie is missing (empty net), goalie_stops is missing. Never replace it with 0.
- Return a copy of df with the new column goalie_stops. Same rows, same order. Do not modify df.
- Use pandas. Include imports and a docstring.
Return only add_goalie_stops_llm and its imports in a Python code block.
"""

In [16]:
stops_context = (
    "First rows of a real tidy DataFrame (game 2022030411), in chronological order:\n\n"
    + reference[reference["game_id"] == 2022030411]
    .head(11)[["game_id", "event_id", "period", "time", "event_type", "goalie", "empty_net"]]
    .to_string(index=False)
)

In [17]:
# Qwen writes add_goalie_stops_llm, we run it and the manual version on the same input, and log both
gen_result = ask_qwen(
    model=model,
    tokenizer=tokenizer,
    log_path=log_path,
    prompt=stops_task,
    context=stops_context,
    profile=PROFILES["gen_tidy"],
    extra={"task_version": "stops_v0", "context_label": "tidy DataFrame sample"},
)
stops_code = extract_text(gen_result["answer"], tag="code")
llm_stops = load_function(stops_code, "add_goalie_stops_llm")  # Qwen's version, the manual one is kept

# Same input for both versions
llm_out = llm_stops(reference)
manual_out = add_goalie_stops(reference)

# Final count per goalie (last value of the counter), side by side
totals = pd.DataFrame({
    "manual": manual_out.dropna(subset=["goalie"]).groupby(["game_id", "goalie"])["goalie_stops"].last(),
    "qwen": llm_out.dropna(subset=["goalie"]).groupby(["game_id", "goalie"])["goalie_stops"].last(),
})
manual_stops = manual_out["goalie_stops"].astype("Float64")
llm_stops_col = pd.to_numeric(llm_out["goalie_stops"]).astype("Float64")
# NaN == NaN counts as identical (empty net rows)
same_rows = ((manual_stops == llm_stops_col).fillna(False) | (manual_stops.isna() & llm_stops_col.isna())).mean()

# Second log record: the manual version and the comparison
log_call(
    log_path,
    messages=[],
    result={"answer": "manual add_goalie_stops (test_tidy_llm.py)", "n_token_out": 0, "duration_s": 0},
    extra={
        "task_version": "stops_v0",
        "qwen_code": stops_code,
        "rows_identical_%": round(100 * same_rows, 1),
        "totals": totals.reset_index().astype(str).to_dict("records"),
    },
)
print(f"Rows identical: {100 * same_rows:.1f} %")
totals

```python
import pandas as pd

def add_goalie_stops_llm(df):
    """
    Add a 'goalie_stops' feature to a tidy DataFrame of NHL shots and goals.

    Parameters:
    df (pd.DataFrame): A DataFrame with one row per shot on goal or goal, in chronological order within each game.
                       Columns include: game_id, event_id, event_type, goalie.
                       event_type is either "shot-on-goal" or "goal".
                       goalie is the goalie's full name, missing when the net is empty.

    Returns:
    pd.DataFrame: A copy of df with an additional column 'goalie_stops' indicating the number of shots stopped
                  by the goalie so far in the game (including the current event).
                  - For "shot-on-goal": increment the goalie's stop count by 1.
                  - For "goal": start the count at 0 (since the shot was not stopped).
                  - If goalie is missing (empty net), goalie_stops is missing (NaN).
    """
    df_copy = df.copy()

    # Group by game_id and goalie to track stops per goalie per game
    # We'll use a dictionary to store the current stop count for each (game_id, goalie) pair
    goalie_stops_dict = {}

    for _, row in df_copy.iterrows():
        game_id = row['game_id']
        goalie = row['goalie']
        event_type = row['event_type']

        # If goalie is missing (empty net), skip setting goalie_stops
        if pd.isna(goalie):
            df_copy.at[row.name, 'goalie_stops'] = pd.NA
            continue

        # Create a key for the game and goalie
        key = (game_id, goalie)

        # Initialize stop count for this goalie in this game if not already present
        if key not in goalie_stops_dict:
            goalie_stops_dict[key] = 0

        # If it's a goal, reset the stop count to 0
        if event_type == "goal":
            goalie_stops_dict[key] = 0
        # If it's a shot-on-goal, increment the stop count
        elif event_type == "shot-on-goal":
            goalie_stops_dict[key] += 1

        # Assign the current stop count to the row
        df_copy.at[row.name, 'goalie_stops'] = goalie_stops_dict[key]

    return df_copy
```

794 tokens in, 521 generated, 105.7 s
Rows identical: 40.3 %

                                manual  qwen
game_id    goalie
2020020007 Mackenzie Blackwood      35   3.0
           Tuukka Rask              20   5.0
2020020020 Anton Khudobin           11   0.0
           Jake Oettinger           27   0.0
           Spencer Knight           26   4.0
2022030411 Adin Hill                33  12.0
           Sergei Bobrovsky         29   5.0